---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - token-rotator.org
  resources:
  - gitlabprojectaccesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - token-rotator.org
  resources:
  - gitlabprojectaccesstokens/finalizers
  verbs:
  - update
- apiGroups:
  - token-rotator.org
  resources:
  - gitlabprojectaccesstokens/status
  verbs:
  - get
  - patch
  - update
