apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: token-rotator
    role: token-resource
  name: tokens.token-rotator.org
spec:
  group: token-rotator.org
  names:
    kind: Token
    listKind: TokenList
    plural: tokens
    singular: token
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          forceNow:
            default: false
            description: Set to true to force a token refresh now
            title: Forcenow
            type: boolean
          name:
            description: The name of the token in k8s
            title: Name
            type: string
          rotationSchedule:
            default: ''
            description: A CronTab text representing when to run
            title: Rotationschedule
            type: string
        type: object
    served: true
    storage: true
