apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: token-rotator
    role: token-resource
  name: tokens.token-rotator.org
spec:
  group: token-rotator.org
  names:
    kind: Token
    listKind: TokenList
    plural: tokens
    singular: token
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          categories:
            anyOf:
            - items:
                type: string
              type: array
            - type: 'null'
            default: null
            description: Any categories to be included in such as `all`
            title: Categories
          forceNow:
            default: false
            description: Set to true to force a token refresh now
            title: Forcenow
            type: boolean
          group:
            anyOf:
            - type: string
            - type: 'null'
            default: token-rotator.org
            description: The kubernetes group the resource is a part of
            title: Group
          kind:
            description: The name of the CRD object
            pattern: ^[A-Za-z\-]*$
            title: Kind
            type: string
          list_kind:
            description: The list naming of the objects
            title: List Kind
            type: string
          name:
            description: The name of the token in k8s
            title: Name
            type: string
          plural:
            description: The plural naming of the objects
            title: Plural
            type: string
          printed_columns:
            anyOf:
            - items:
                $ref: '#/$defs/CRDPrinterColumn'
              type: array
            - type: 'null'
            default: null
            title: Printed Columns
          rotationSchedule:
            default: ''
            description: A CronTab text representing when to run
            title: Rotationschedule
            type: string
          scope:
            anyOf:
            - enum:
              - Namespaced
              - Cluster
              type: string
            - type: 'null'
            default: Namespaced
            description: If the CRD is namespace scoped or cluster-wide
            title: Scope
          short_names:
            anyOf:
            - items:
                type: string
              type: array
            - type: 'null'
            default: null
            description: A list of short names to use with kubectl
            title: Short Names
          singular:
            description: The singular naming of the object
            title: Singular
            type: string
        type: object
    served: true
    storage: true
