apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tokens.token-rotator.org
spec:
  group: token-rotator.org
  names:
    categories:
    - all
    - token
    kind: Token
    listKind: TokenList
    plural: tokens
    shortNames: []
    singular: token
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The cron spec defining the interval a CronJob is run
      format: ''
      jsonPath: .spec.cronSpec
      name: Spec
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources '
            title: Apiversion
            type: string
          forceNow:
            default: false
            title: Forcenow
            type: boolean
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds '
            title: Kind
            type: string
          name:
            title: Name
            type: string
          rotationSchedule:
            title: Rotationschedule
            type: string
          type:
            title: Type
            type: string
          value:
            title: Value
            type: string
        required:
        - apiVersion
        - kind
        - name
        - value
        - type
        - rotationSchedule
        title: Token
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
