apiVersion: token-rotator.org/v1alpha1
kind: GitLabProjectAccessToken
metadata:
  labels:
    app.kubernetes.io/name: token-rotator
    app.kubernetes.io/managed-by: kustomize
  name: ci-bot
spec:
  project: mygroup/myproject
  accessLevel: Maintainer
  scopes:
    - api
    - read_registry
  rotationSchedule: "0 0 1 * *"
  rotationStrategy: Immediate
  apiTokenSecretRef:
    name: gitlab-api-credentials
    key: token
  export:
    type: Secret
    name: gitlab-ci-token
    namespace: default
